language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="github"
   - REVDEPS=true
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.02.3
   - DISTRO=debian-testing OCAML_VERSION=4.02.3
   - DISTRO=debian-unstable OCAML_VERSION=4.04.0
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.02.3
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-6 OCAML_VERSION=4.02.3
   - DISTRO=centos-7 OCAML_VERSION=4.02.3
   - DISTRO=fedora-24 OCAML_VERSION=4.02.3
   - DISTRO=alpine-3.4 OCAML_VERSION=4.03.0
